print('회원정보를 입력하세요.')
userName = input('이름 :')
userMail = input('메일 :')
userId = input('아이디 :')
userPw = input('비밀번호')
print('-----------------------------------')
print('To.' + userMail)
print('▶ 아이디 및 비밀번호 확인')
print(userName + '고객님 안녕하세요.')
print(userName + '고객님의 아이디와 비밀번호는 아래와 같습니다.')
print('아이디 : ' + userId)
print('비밀번호 : ' +  userPw)
print('-----------------------------------')

